services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env
    ports:
      - "5432:5432"
  database_test:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env.test
    ports:
      - "5433:5432"